name: cached_text_editing_controller
description: "A Flutter package providing a TextEditingController with efficient text modification tracking and comparison capabilities."
version: 1.0.1
homepage: https://github.com/Musaddiq625
repository: https://github.com/Musaddiq625/cached_text_editing_controller
issue_tracker: https://github.com/Musaddiq625/cached_text_editing_controller/issues

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0